namespace MDSF.BuildingBlocks.Globalization
{
    public interface ITextResource
    {
        string Id { get; }
        string Request { get; }
        string Appliance { get; }
        string Category { get; }
        string PropertyKey { get; }
        string File { get; }
        string PropertyValue { get; }
        string AddProperty { get; }
        string ById { get; }
        string PropertyKeyName { get; }
        string Title { get; }
        string Tag { get; }
        string Done { get; }
        string NotDone { get; }
        string Send { get; }
        string Save { get; }
        string SaveReplay { get; }
        string Replay { get; }
        string Add { get; }
        string Edit { get; }
        string View { get; }
        string NoImage { get; }
        string NoPublish { get; }
        string Categories { get; }
        string ContentAddOrEdit { get; }
        string Search { get; }
        string ExportQualityCodes { get; }
        string SkdSaloon { get; }
        string QualityCodes { get; }
        string QualityRegisteredUser { get; }
        string ProductionYear { get; }
        string Delete { get; }
        string Refresh { get; }
        string ProcessDesc { get; }
        string Value { get; }
        string ToodooziDesc { get; }
        string Property { get; }
        string Properties { get; }
        string Permission { get; }
        string Role { get; }
        string InvalidCredentials { get; }
        string InvalidReturnUrl { get; }
        string PJI { get; }
        string SubClassCode { get; }
        string SubClassDesc { get; }
        string Page { get; }
        string IsLeaf { get; }
        string Select { get; }
        string OrderTypeDesF { get; }
        string DamNo { get; }
        string SelectSmallImage { get; }
        string SelectLargImage { get; }
        string Upload { get; }
        string Cancel { get; }
        string NoSelect { get; }
        string SelectValueType { get; }
        string SelectType { get; }
        string SelectSaloon { get; }
        string NewSaloon { get; }
        string CurrentSaloon { get; }
        string SelectSteps { get; }
        string RegisterDate { get; }
        string CurrentSteps { get; }
        string NewSteps { get; }
        string AddToRoot { get; }
        string BlockedByQC { get; }
        string OrderNo { get; }
        string QRCode { get; }
        string OF { get; }
        string Note { get; }
        string LoadNo { get; }
        string LastProductionStepDesc { get; }
        string EngineNO { get; }
        string ColorDesc { get; }
        string Description { get; }
        string TwoColorRoof { get; }
        string Print { get; }
        string CarClassDesc { get; }
        string CarClassCode { get; }
        string ProductStatistics { get; }
        string ProductCount { get; }
        string Line { get; }
        string CarModelDesc { get; }
        string CarModelCode { get; }
        string NewestProduct { get; }
        string VF { get; }
        string VIN { get; }
        string ExpireDateTime { get; }
        string Date { get; }
        string BodyNo { get; }
        string Publish { get; }
        string Enable { get; }
        string ShowInFirstPage { get; }
        string Count { get; }
        string EnterToPaintshop { get; }
        string AcceptPaintshop { get; }
        string Siler { get; }
        string EnterToSaloon { get; }
        string PBS { get; }
        string UpdateTime { get; }
        string Exite { get; }
        string Content { get; }
        string User { get; }
        string Vote { get; }
        string Customer { get; }
        string Mobile { get; }
        string SKDSaloonDesF { get; }
        string Name { get; }
        string Username { get; }
        string LastName { get; }
        string LoginToYourAccount { get; }
        string Logout { get; }
        string Loading { get; }
        string YouAreNowLoggedOut { get; }
        string Email { get; }
        string Password { get; }
        string PasswordConfirm { get; }
        string CaptchaCode { get; }
        string EnterTheCode { get; }
        string RememberMe { get; }
        string ForgotPassword { get; }
        string Login { get; }
        string Signup { get; }
        string ChangePassword { get; }
        string SendVerifictionCode { get; }
        string SendForgotPasswordCode { get; }
        string Return { get; }
        string Image { get; }
        string LatinName { get; }
        string SelectImages { get; }
        string NoneLeafCategoryCanNotHaveDiscount { get; }
        string Country { get; }
        string BuilderCountry { get; }
        string Brand { get; }
        string BrandName { get; }
        string AddBrand { get; }
        string OpreationIsSuccess { get; }
        string FirstChooseCategory { get; }
        string FirstChoosePage { get; }
        string ChossenCategoryIsNotLeaf { get; }
        string TryAgain { get; }
        string ExchangeRate { get; }
        string EmailCode { get; }
        string EmailConfirmationCodeExpire { get; }
        string EmailChangePasswordCodeExpire { get; }
        string Profile { get; }
        string Wellcome { get; }
        string Comment { get; }
        string FunctionLocation { get; }
        string Comments { get; }
        string NoRecords { get; }
        string SaveCommentOrAsk { get; }
        string ECommerceIntegratedSystems { get; }
        string Accesses { get; }
        string StoreManagement { get; }
        string SaleManagement { get; }
        string CMSManagement { get; }
        string AccountManagement { get; }
        string ImageManagement { get; }
        string Version { get; }
        string DiscountManagement { get; }
        string ExchangeRateManagement { get; }
        string BrandManagement { get; }
        string ApplianceManagement { get; }
        string CategoryManagement { get; }
        string PropertyManagement { get; }
        string AddCategory { get; }
        string EditCategory { get; }
        string PermissionManagement { get; }
        string RoleManagement { get; }
        string UserManagement { get; }
        string ForReturn { get; }
        string Click { get; }
        string Here { get; }
        string BodyInfo { get; }
        string SaveData { get; }
        string SaveStep { get; }
        string SFC { get; }
        string ProductionFlow { get; }
        string SelectSaloonsAndStep { get; }
        string AccessDenied { get; }
        string AccessDeniedByDariche { get; }
        string TheOprationSuccessfullyComplete { get; }
        string TheCommandHasNoEffect { get; }
        string Synchron { get; }
        string ReadyPrintSynchrons { get; }
        string ReadyPrintSynchronsDate { get; }
        string BodyNoProperty { get; }
        string NotValidBodyNo { get; }
        string BodyNoAllReadyExist { get; }
        string NotValidBodyNoStruct { get; }
        string BodyNoNotUseInThisSaloon { get; }
        string VdsByBodyNoNotFound { get; }
        string NoCodeExistForVDS { get; }
        string CanNotCreateVIN { get; }
        string CanNotCreateBodyOnThisSaloon { get; }
        string NoProductionFlowForThisModel { get; }
        string AllStepForThatCarAllReadyRegistered { get; }
        string BodyNoIsNew { get; }
        string ProductIsDeposit { get; }
        string UnStatedProduct { get; }
        string WasteProduct { get; }
        string SendingOutProduct { get; }

        string GetWindowsShellInfo { get; }
        string Start { get; }
        string InvalidFormt { get; }
        string SynchronWindowsAppInfoReadyToDownload { get; }

        string DescState { get; }
        string EngineHistory { get; }
        string BodyNumber { get; }
        string EngineTypeCode { get; }
        string EngineTypeDesF { get; }
        string BranchDesF { get; }
        string Part { get; }
        string PartCode { get; }
        string PartNumber { get; }
        string StateDesF { get; }
        string SaloonDesF { get; }
        string Saloon { get; }
        string LastStateSerialNo { get; }
        string UnsuccessfulMessage { get; }
        string EnterTheBIWSite { get; }
        string EnterThePaintShop { get; }
        string OpreationIsfailure { get; }
        string BIWSiteSaloon { get; }
        string PaintShopSaloon { get; }
        string CarSubClassDesc { get; }
        string SearchConditions { get; }
        string SafeQualityParts { get; }
        string PreAssignmentOFAutomatic { get; }
        string SelectedOFQty { get; }
        string SearchByOF { get; }
        string ColorCode { get; }
        string Close { get; }
        string PreAssignment { get; }
        string SendToExcel { get; }
        string RemoveSearchConditions { get; }
        string ShowAlarmPage { get; }
        string NewUserRegitered { get; }
        string AddFilters { get; }
        string Confirmation { get; }
        string ViewResultsPreAssignment { get; }
        string PreviewIN { get; }
        string ErrorDesc { get; }

        string DatePlanning { get; }
        string Plan { get; }
        string Pallet { get; }
        string WorkGroup { get; }
        string ThePlan { get; }
        string CreateFile { get; }
        string PlaqueEngraving { get; }
        string BodyEngraving { get; }
        string Erorr { get; }
        string RowNumber { get; }
        string Quality { get; }
        string Status { get; }
        string CreateDate { get; }

        string NoStepRegistrationForThisProductOnThisSaloon(string message);
        string SelectJustOneItem(string message);
        string NotFound(string name, string id);
        string SelectJustOneItemForEdit(string message);
        string SelectItemForEdit(string message);
        string SelectItem(string message);
        string ValueCanNotBeEmpty(string message);
        string AlreadyExist(string name, Guid id);
        string SynchronQueuesMessage { get; }

    }
}